### ISSUE TITLE
Decide fate of repository

### ISSUE THREAD

**Issue by mojavelinux** [mgreau/asciidoctor-wildfly-docker#1]
@robertpanzer @mgreau We need to decide on the fate of this repository since it's not currently being maintained. Here are a couple of proposals:

1. Archive it.

2. Treat the repository as a documentation example. This means updating the repository, adding a page to the documentation about what it is demonstrating, and make sure it's being tested with each release of AsciidoctorJ. In that case, I might also rename it to asciidoctorj-servlet-example or something. We could even stop coupling it with Docker and just make it a standalone Servlet project with a Maven or Gradle build.

3. Morph it into a Docker image that provides AsciidoctorJ to be used from the command line. I realize that would serve a different objective than what it's currently used for. But it would be more aligned with what the name suggests. (An alternative would be to add a Dockerfile to the asciidoctorj-distribution).

Please comment with suggestions about how to proceed.

**Comment by mojavelinux** [comment]
I do think there is a place in the AsciidoctorJ documentation that shows how to use AsciidoctorJ in a Servlet (or any sort of Java EE or Spring application).

**Comment by robertpanzer** [comment]
I would currently vote for 2 + 3.

I had a short look at the repository and it in its current form it seems to be sth like an integration test for AsciidoctorJ running in Wildfly.
It would be great if we could update it to the latest versions and keep it updated. 
Maybe even pull this as an integration test into the AsciidoctorJ repo?
I spent a few minutes trying to get it running on my machine, but didn't have much luck on the first attempt. 
It looks like I have to level up my Arquillian Cube Know-how.

Additionally we could also do 3.

**Comment by mojavelinux** [comment]
With the documentation moving to Antora, there will be plenty of room for a page dedicated to using AsciidoctorJ in a Servlet, which is where the example would come in. The more I think about it, the more I feel that Docker is just getting in the way here. It seems like this is simple enough to get running in a regular Java project. And I agree, that would then make a nice test for AsciidoctorJ.

Since we already have the sdkman and Chocolately configs in the asciidoctorj repository, perhaps a Docker container that allows you to run the asciidoctorj command would belong there as well. (The alternative is to move all the packaging to separate repositories, but perhaps that's a next step).

**Comment by robertpanzer** [comment]
I think Wildfly takes a special position here due to its requirement to run AsciidoctorJ as a module which makes things complicated here.
Do you know if it's possible to add modules to a Arquillian Wildfly test instance?

> Since we already have the sdkman and Chocolately configs in the asciidoctorj repository, perhaps a Docker container that allows you to run the asciidoctorj command would belong there as well.

:+1:

**Comment by mojavelinux** [comment]
> I think Wildfly takes a special position here due to its requirement to run AsciidoctorJ as a module which makes things complicated here.

Good point.

> Do you know if it's possible to add modules to a Arquillian Wildfly test instance?

Perhaps ping the current Arquillian team about that one.

**Comment by mgreau** [comment]
@mojavelinux @robertpanzer Hi, sorry to be late here and not active anymore, for now, in the asciidoctor community.

I'd vote for 1. or 2.

For 3. I'm not sure why users would like to use a Docker image with `asciidoctorj` while we have already an official Docker image. Maybe I'm wrong but I think it could be confusing.

> 2. Treat the repository as a documentation example. This means updating the repository, adding a page to the documentation about what it is demonstrating, and make sure it's being tested with each release of AsciidoctorJ. In that case, I might also rename it to asciidoctorj-servlet-example 

I like this idea, but unfortunately, I do not think I'll have the time to do this update. That's why I'm ok with 1.

**Comment by robertpanzer** [comment]
We have the second point integrated now into the AsciidoctorJ test suite, it doesn't run on the CI systems because it doesn't look like there are versions of Wildfly retrievable from Maven Central, but the test can be run locally.

**Comment by mojavelinux** [comment]
@robertpanzer I'm glad to hear that it's covered by a test. That's a good start. However, given that you are saying it can't run because of the unavailability of Wildfly, is it really even useful anymore?

I'm prepared to move forward with archiving this project. If there's a statement you'd like me to add to the README before I do so, please reply. Otherwise, we'll archive it with no statement.

**Comment by robertpanzer** [comment]
I can't remember what issues I had at that time with wildfly, but these should be resolved now.
The CI runs integration tests with Wildfly and Spring Boot.
So I'd be fine with archiving the project.

**Comment by mojavelinux** [comment]
Sounds good. Thanks for following up.
